default: &default
  adapter: postgresql
  encoding: unicode
  host: db
  username: <%= ENV['DATABASE_USER'] %>
  password: <%= ENV['DATABASE_PASSWORD'] %>
  pool: 5

development:
  <<: *default
  database: portfolio_1_development

test:
  <<: *default
  database: portfolio_1_test
